image:
  - Visual Studio 2017

stack: python 3.7

cache:
  - '%LOCALAPPDATA%\pip\Cache'

environment:
  matrix:
    - platform: x86
      LIBFTDI: "libftdi1-1.4git_devkit_x86_x64_14June2018/bin32/*.dll"
      PYTHON_HOME: C:\Python37
      PYTHON_VERSION: '3.7'
      PYTHON_ARCH: '32'

build: off

install:
  - ps: Invoke-WebRequest -Uri 'https://sourceforge.net/projects/picusb/files/libftdi1-1.4git_devkit_x86_x64_14June2018.zip' -OutFile libftdi1-1.4git_devkit_x86_x64_14June2018.zip -UserAgent [Microsoft.PowerShell.Commands.PSUserAgent]::Chrome
  - cmd: 7z x libftdi1-1.4git_devkit_x86_x64_14June2018.zip
  - cmd: '%PYTHON_HOME%\Scripts\pip install pywin32 pylibftdi pydispatcher wxPython pyinstaller requests'

build_script:
  - cmd: '%PYTHON_HOME%\python -m PyInstaller --onefile --clean --add-binary images/*;images --add-binary %LIBFTDI%;. HondaECU.py --name HondaECU --icon=images/honda.ico'
  - cmd: '%PYTHON_HOME%\python -m PyInstaller --onefile --clean --add-binary %LIBFTDI%;. log.py --name log --icon=images/honda.ico'

artifacts:
  - path: dist\*

deploy:
  provider: GitHub
  description: 'A diagnostic and flashing tool for Honda ECUs'
  auth_token:
    secure: VDADKxNk9UEQ11Ycj0bjwqi5yzJKuKOZ+qAWu5vfPqSQTeJDiCoqWSuCLYK1o2pC
  artifact: /.*\.exe/
  draft: false
  prerelease: false
  on:
    branch: master
    appveyor_repo_tag: true
